default:
  image: python:3.9

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - poetry build

build-code-test:
  stage: test
  script:
    - poetry run pytest
