default:
  image: python:3.9

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - poetry build

build-code-test:
  stage: test
  script:
    - poetry run pytest

testing:
  stage: test
  script:
    - poetry run pytest --verbose --junit-xml=report.xml --cov --cov-fail-under=100
  artifacts:
    when: always
    reports:
      junit: /builds/croy/python-devop/tests/report.xml